version: '2'

services:
  workspace:
    image: busybox:latest
    volumes:
      - ${APPLICATION}:/var/www
      - ./mariadb:/var/lib/mysql:rw
      - ./services/nginx/logs:/var/log/nginx
      - ./services/nginx/sites:/etc/nginx/conf.d
  php-fpm:
    build:
      context: ./services/php
      args:
        - "XDEBUG_ON=${XDEBUG_ON}"
        - "XDEBUG_REMOTE_HOST=${XDEBUG_REMOTE_HOST}"
    ports:
      - 9000
    volumes_from:
      - workspace
    restart: always
    extra_hosts:
       - "sandbox.slim.local:10.5.0.5"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4

  composer:
    build:
      context: ./services/composer
    volumes:
      - ./:/app

  nginx:
    build:
      context: ./services/nginx
    volumes_from:
      - workspace
    ports:
      - 8080:80
    depends_on:
      - php-fpm
    restart: always
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5

  mariadb:
    build:
      context: ./services/mariadb
    ports:
      - 3306:3306
    volumes_from:
      - workspace
    environment:
      - "MYSQL_DATABASE=app"
      - "MYSQL_USER=app"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
  
  redis:
    build: ./services/redis
    volumes_from:
      - workspace
    ports:
      - "6379:6379"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7
    
  mongo:
    build: ./services/mongo
    ports:
      - "27017:27017"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.8

  node:
    build:
      context: ./services/node
    volumes_from:
      - workspace

volumes:
  php-fpm:
    driver: "local"
  nginx:
    driver: "local"
  mariadb:
    driver: "local"
  node:
    driver: "local"

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1